# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: './build/libs/'
    publishLocation: 'pipeline'
- task: FtpUpload@2
  inputs:
    credentialsOption: 'serviceEndpoint'
    serverEndpoint: 'NVCLAnalyticsServerFTP'
    rootDirectory: './build/libs/'
    filePatterns: 'app.jar'
    remoteDirectory: '/site/wwwroot/'
    clean: false
    cleanContents: false
    preservePaths: false
    trustSSL: false